### ISSUE TITLE
Username and Password Rabbit

### ISSUE THREAD

**Issue by az1fr3** [mehmetkirkoca/social-media-manager#3]
I Manage to setup but when i open the localhost its ask me for a username paswoord, any of default of rabbit wont work.

**Comment by mehmetkirkoca** [comment]
In our project's docker-compose.yml file, the default parameters for RabbitMQ are set as follows:
RABBITMQ_DEFAULT_USER: username
RABBITMQ_DEFAULT_PASS: password

The interface should not ask for any password. Access the interface at URL: http://localhost:8081
